# Generated by Django 5.0.2 on 2024-03-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionsFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection_factor', models.CharField(max_length=30)),
                ('protection_factor_value', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'protections_factors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.ImageField(upload_to='maps')),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Maps_Campaigns', to='campaigns.campaigns')),
            ],
            options={
                'db_table': 'maps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Obstacles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obstacle', models.CharField(max_length=100)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('map_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Obstacles_Maps', to='maps.maps')),
            ],
            options={
                'db_table': 'obstacles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Protections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection', models.CharField(max_length=100)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('map_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Protections_Maps', to='maps.maps')),
                ('protection_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Protections_ProtectionFactors', to='maps.protectionsfactors')),
            ],
            options={
                'db_table': 'protections',
                'managed': True,
            },
        ),
    ]
