# Generated by Django 5.0.2 on 2024-04-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protections',
            name='cell_size',
            field=models.IntegerField(default=45),
        ),
    ]
