# Generated by Django 5.0.2 on 2024-04-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_protections_cell_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='actual',
            field=models.BooleanField(default=False),
        ),
    ]
