# Generated by Django 5.0.2 on 2024-03-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rune_quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('base_value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rq_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CharactersSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CharactersSkills_RuneQuest', to='rune_quest.runequest')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CharactersSkills_SkillsModifiers', to='rune_quest.skillsmodifiers')),
            ],
            options={
                'db_table': 'rq_character_skills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=300)),
                ('base_value', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Skills_Categories', to='rune_quest.categories')),
            ],
            options={
                'db_table': 'rq_skills',
                'managed': True,
            },
        ),
    ]
