# Generated by Django 5.0.2 on 2024-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rune_quest', '0003_skills_annotations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='annotations',
        ),
        migrations.AddField(
            model_name='charactersskills',
            name='annotations',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
