# Generated by Django 5.0.2 on 2024-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rune_quest', '0004_remove_skills_annotations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersskills',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
