# Generated by Django 5.0.2 on 2024-03-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rune_quest', '0005_charactersskills_checked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharactersSkills',
            new_name='CharacterSkills',
        ),
    ]
