# Generated by Django 5.0.2 on 2024-03-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rune_quest', '0007_skillresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillresults',
            name='critical_success',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='skillresults',
            name='fumble',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='skillresults',
            name='special_success',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
