# Generated by Django 5.0.2 on 2024-03-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rune_quest', '0008_alter_skillresults_critical_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
