# Generated by Django 5.0.2 on 2024-03-07 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rune_quest', '0010_magic_magicspells'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_category', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'rq_weapon_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WeaponModifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_mod', models.IntegerField(default=0)),
                ('parry_mod', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeaponModifiers_RuneQuest', to='rune_quest.runequest')),
            ],
            options={
                'db_table': 'rq_weapon_modifiers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=100)),
                ('damage', models.CharField(max_length=20)),
                ('min_str', models.IntegerField(default=0)),
                ('min_dex', models.IntegerField(default=0)),
                ('enc', models.IntegerField(default=0)),
                ('base_chance', models.IntegerField(default=0)),
                ('armor_points', models.IntegerField(default=0)),
                ('strike_rank', models.IntegerField(default=0)),
                ('weapon_range_effective', models.IntegerField(default=0)),
                ('weapon_range_max', models.IntegerField(default=0)),
                ('weapon_rate_of_fire', models.CharField(max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Weapons_WeaponCategories', to='rune_quest.weaponcategories')),
            ],
            options={
                'db_table': 'rq_weapons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WeaponsSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_rank', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('parry', models.IntegerField(default=0)),
                ('armor_points', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeaponSkills_RuneQuest', to='rune_quest.runequest')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeaponsCarried_Weapons', to='rune_quest.weapons')),
            ],
            options={
                'db_table': 'rq_weapon_skills',
                'managed': True,
            },
        ),
    ]
