# Generated by Django 5.0.2 on 2024-03-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rune_quest', '0011_weaponcategories_weaponmodifiers_weapons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponsskills',
            name='checked_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weaponsskills',
            name='checked_parry',
            field=models.BooleanField(default=False),
        ),
    ]
