# Generated by Django 5.0.2 on 2024-02-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavageWorlds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventurer_name', models.CharField(max_length=50)),
                ('character_name', models.CharField(max_length=50)),
                ('xp', models.IntegerField(default=0)),
                ('rank', models.CharField(choices=[('nov', 'novice'), ('sea', 'seasoned'), ('vet', 'veteran'), ('her', 'heroic'), ('leg', 'legendary')], max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('bennies', models.IntegerField(default=0)),
                ('convinction', models.TextField(blank=True, null=True)),
                ('agility', models.IntegerField(default=4)),
                ('smarts', models.IntegerField(default=4)),
                ('spirit', models.IntegerField(default=4)),
                ('strength', models.IntegerField(default=4)),
                ('vigor', models.IntegerField(default=4)),
                ('charisma', models.IntegerField(default=0)),
                ('pace', models.IntegerField(default=0)),
                ('parry', models.IntegerField(default=4)),
                ('reason', models.IntegerField(default=0)),
                ('toughness', models.IntegerField(default=4)),
                ('hindrances', models.JSONField(verbose_name={})),
                ('edges', models.JSONField(verbose_name={})),
                ('skills', models.JSONField(verbose_name={})),
                ('armour', models.JSONField(verbose_name={})),
                ('weapons', models.JSONField(verbose_name={})),
                ('possessions', models.JSONField(verbose_name={})),
                ('extra_equipments', models.JSONField(verbose_name={})),
                ('power', models.IntegerField(default=0)),
                ('wounds', models.IntegerField(default=0)),
                ('fatigue', models.IntegerField(default=0)),
                ('bullets', models.JSONField(verbose_name={})),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SavageWorlds_Campaigns', to='campaigns.campaigns')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SavageWorlds_Players', to='players.players')),
            ],
            options={
                'db_table': 'savage_worlds',
                'managed': True,
            },
        ),
    ]
