# Generated by Django 5.0.2 on 2024-03-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltokens',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='tokens',
            name='campaign',
        ),
    ]
