# Generated by Django 5.0.2 on 2024-04-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_historicaltokens_name_tokens_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltokens',
            name='actual_fow_range',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicaltokens',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('do', 'Down'), ('le', 'Left'), ('ri', 'Right'), ('ul', 'Up Left'), ('ur', 'Up Right'), ('dl', 'Down Left'), ('dr', 'Down Right')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicaltokens',
            name='direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltokens',
            name='direction_fow',
            field=models.CharField(choices=[('fon', 'Front Only'), ('cir', 'circular'), ('fan', 'flat angle')], default='cir', max_length=3),
        ),
        migrations.AddField(
            model_name='tokens',
            name='actual_fow_range',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tokens',
            name='current_direction',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('do', 'Down'), ('le', 'Left'), ('ri', 'Right'), ('ul', 'Up Left'), ('ur', 'Up Right'), ('dl', 'Down Left'), ('dr', 'Down Right')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tokens',
            name='direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokens',
            name='direction_fow',
            field=models.CharField(choices=[('fon', 'Front Only'), ('cir', 'circular'), ('fan', 'flat angle')], default='cir', max_length=3),
        ),
    ]
