# Generated by Django 5.0.2 on 2024-04-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('tokens', '0004_historicaltokens_actual_fow_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltokens',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='campaigns.campaigns'),
        ),
        migrations.AddField(
            model_name='tokens',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Tokens_Campaigns', to='campaigns.campaigns'),
            preserve_default=False,
        ),
    ]
