# Generated by Django 5.0.2 on 2024-02-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('role_systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('available_seats', models.IntegerField(default=0)),
                ('max_seats', models.IntegerField(default=1)),
                ('weekday_fixed', models.BooleanField(default=False)),
                ('playing_weekdays', models.JSONField(blank=True, null=True, verbose_name={'Fri': False, 'Mon': False, 'Sat': False, 'Sun': False, 'Thu': False, 'Tue': False, 'Wed': False})),
                ('multi_seat', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('master', models.ManyToManyField(related_name='Campaigns_Players', to='players.players')),
                ('role_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Campaigns_RoleSystems', to='role_systems.rolesystems')),
            ],
            options={
                'db_table': 'campaigns',
                'managed': True,
            },
        ),
    ]
